export const courseData = {
  data: {
    title: "Our courses",
    db_data: "course_categories",
    img: "/uploads/our_courses_680f2bcaae.jpg",
    course_categories: [
      {
        id: 1,
        category: "International Foundation Programme",
        description:
          "<p>The International Foundation Programme is a 30 week programme designed for students who wish to study at Middlesex University Dubai but who may not meet the necessary entry requirements for direct entry onto one of our undergraduate programmes. The IFP prepares students for enrolment onto one of our many Bachelor’s Degrees and allows them to settle into life on campus and bridge the gap between high school and university education. Students can choose to specialise in Business, Law and Politics, Psychology, Arts and Media, or Engineering and Computer Informatics.</p>",
        icon: "/uploads/Foundation_Programmes_f1f7b1dc86.svg",
        code: "",
        slug: "ifp",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Foundation_Programmes_f1f7b1dc86.svg",
        banner_title: "International Foundation Programme",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Foundation_Programmes_f1f7b1dc86.svg",
        links: "ifp",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Business",
        description:
          "<p>The Business School has been a major provider of business, management and professional accredited programmes for more than a decade, with a sound record of working in partnership with public and private sector organisations within the UAE. Designed to meet the needs of employers and organisations, students develop into professionals who are able to manage ethically, sensitively and holistically across a range of sectors.</p>",
        icon: "/uploads/Business_icon_a744e3f291.svg",
        code: "",
        slug: "courses-business",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Business_icon_a744e3f291.svg",
        banner_title: "Business",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Business_icon_a744e3f291.svg",
        links: "courses/business",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Accounting and Finance",
        description:
          "<p>Our Accounting and Finance programmes are recognised globally as offering excellent preparation for professionals in the field. Our team consists of a diverse group of internationally qualified and renowned scholars and practitioners who specialise in key discipline areas including management accounting, banking regulations, corporate finance, econometrics, data analytics and many more. The department puts a strong emphasis on employability and we have developed strong industry links. Our expert academic staff consult for leaders in business and government. Our learning facilities are state-of-the-art and we have received recognition of our programmes from some of the world’s leading professional bodies including the ACCA, UAECA, CIMA, CFA, CIPFA, GARP and ICAEW. We aim to produce leading research that impacts policy and practice.&nbsp;</p>",
        icon: "/uploads/ACCOUNTING_and_FINANCE_ec78c44210.svg",
        code: "",
        slug: "courses-accounting-and-finance",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/ACCOUNTING_and_FINANCE_ec78c44210.svg",
        banner_title: "Accounting and Finance",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url:
          "/uploads/ACCOUNTING_and_FINANCE_ec78c44210.svg",
        links: "courses/accounting-and-finance",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Health and Education",
        description:
          "<p>Middlesex University Dubai’s School of Health and Education covers many areas of study including sociology, leadership, management, curriculum studies, best practice and child developments. Students are encourage to self-reflect and be able to identify and articulate their personal competencies through the many varied opportunities provided, along with the benefit of studying in a rich, diverse and culturally stimulating setting. Graduates of these programmes hold a well-developed selection of skills including communication, problem-solving and teamwork.</p>",
        icon: "/uploads/Health_and_ducation_125fce6f49.svg",
        code: "",
        slug: "courses-education",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Health_and_ducation_125fce6f49.svg",
        banner_title: "Health and Education",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Health_and_ducation_125fce6f49.svg",
        links: "courses/education",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Psychology",
        description:
          "<p>The Department of Psychology offers a solid grounding in modern psychology through a mixture of theoretical and professional practice, offering the opportunity to specialise in a range of pathways. Our students are encouraged to consider how psychology interacts with other academic disciplines such as Human Resource Management, Marketing, Education and Crimonology, equipping them to pursue global careers in a range of industries where an applied knowledge of human behaviour and experiences will ensure they stand out to potential employers. Students also gain exposure to the world of clinical , counseling, health, and industrial psychology and develop the counselling and interpersonal skills needed to undertake further postgraduate training to practice as clinical, counselling, health, and industrial psychologists.</p>",
        icon: "/uploads/Psychology_8eb13bc9da.svg",
        code: "",
        slug: "courses-psychology",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Psychology_8eb13bc9da.svg",
        banner_title: "Psychology",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Psychology_8eb13bc9da.svg",
        links: "courses/psychology",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Computer Engineering and Informatics",
        description:
          "<p>The Department of Computer Engineering and Informatics at Middlesex University Dubai encompasses modern engineering, technology and computing taught by award-winning faculty with decades of collective industry and academic experience. Our students are given an edge through partnerships with leading STEM organisations in the Middle East and around the world and are able to pursue coveted industry qualifications as part of their curriculum. Through leading research conducted by our Centre for Innovation in Human Experience, students are also exposed to cutting-edge technologies and concepts such as Artificial Intelligence, Robotics and Data Science during their studies, equipping them to pursue global, impactful careers in this in-demand field. We invite you to read our annual newsletter, MDX.STREAM, which highlights the our department’s activities.</p>",
        icon: "/uploads/Computer_Engineering_0c97b6afba.svg",
        code: "",
        slug: "courses-computer-engineering-and-informatics",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Computer_Engineering_0c97b6afba.svg",
        banner_title: "Computer Engineering and Informatics",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Computer_Engineering_0c97b6afba.svg",
        links: "courses/computer-engineering-and-informatics",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Media",
        description:
          "<p>Recognised as the ‘Best Media Centre’ in the region by Forbes Middle East (2019), Middlesex University Dubai’s School of Media directly responds to the ever-changing ways in which we communicate. These vibrant programmes are taught by expert faculty with an array of industry experience, bring a diverse range of skillsets and knowledge to the classroom. Students are encouraged to participate in internships, field trips and competitions, and have won various awards at events such as the Dubai Lynx Festival of Creativity and the Dubai Film Festival.</p>",
        icon: "/uploads/Media_80d2bf2a3a.svg",
        code: "",
        slug: "courses-media",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Media_80d2bf2a3a.svg",
        banner_title: "Media",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Media_80d2bf2a3a.svg",
        links: "courses/media",
        banner_image_full_url: "",
      },
      {
        id: 1,
        category: "Art and Design",
        description:
          "<p>The School of Art and Design at Middlesex University Dubai comprises of Graphic Design and Fashion Design. The programmes are taught in state-of-the-art design labs and our newly built Fashion Studio featuring its very own runway. Students are exposed to a variety of design mediums and encourage to build their technical skills and discover their design identity.</p>",
        icon: "/uploads/Art_and_Design_d6061f0374.svg",
        code: "",
        slug: "courses-art-and-design",
        content_sub_title: "middlesex university",
        content_title: "overview",
        banner_image: "/uploads/Art_and_Design_d6061f0374.svg",
        banner_title: "Art and Design",
        is_active: 1,
        created_by: null,
        updated_by: 1,
        deleted_at: null,
        created_at: "2022-07-27T06:53:09.000000Z",
        updated_at: "2022-07-27T07:11:22.000000Z",
        category_icon_full_url: "/uploads/Art_and_Design_d6061f0374.svg",
        links: "courses/art-and-design",
        banner_image_full_url: "",
      },
    ],
    slider: [
      {
        image: "/uploads/our_courses_680f2bcaae.jpg",
        title: "ABC",
      },
      {
        image: "",
        title: "DEF",
      },
      {
        image: "",
        title: "GHi",
      },
    ],
  },
};
