import Assets from "../components/Layout/CommonLayout/assets";

export const data = {
  data: {
    header_script: null,
    custom_css: null,
    no_follow: false,
    no_index: false,
    cta_enabled: false,
    enable_header: true,
    enable_footer: true,
    widgets: [
      {
        slug: "mdx_inner_banner",
        data: {
          course_page: true,
          sub_title: "UNDERGRADUATE",
          title: "BA HONOURS ACCOUNTING AND FINANCE",
          content:
            "<p>The BA (Honours) Accounting and Finance gives you the tools to succeed in this dynamic and rewarding profession.</p><p>You will develop advanced theoretical and practical knowledge of accounting and finance. This programme is the ideal first step to becoming a qualified accountant, covering key areas within financial and management accounting, taxation and business law. You will gain a deep understanding of the role accounting plays in successful organisations.</p>",
          img: {
            url: "/uploads/IFP_September_2021_ab674e4a49.png",
            alt: "UNDERGRADUATE",
          },
          mobile_banner_img: "",
          buttons: [
            {
              label: "Apply Now",
              link: "https://www.mdx.ac.ae/app-portal",
              color: "primary",
            },
          ],
          course_strip: [
            {
              slug: "start",
              title: "SEPTEMBER",
              sub_title: "",
              icon: "",
            },
            {
              slug: "duration",
              title: "DURATION",
              sub_title: "3 YEARS",
              icon: "",
            },
            {
              slug: "attendance",
              title: "ATTENDANCE",
              sub_title: "Full Time",
              icon: "",
            },
            {
              slug: "course_leader",
              title: "DR PALLAVI KISHORE FCCA UAECA SFHEA",
              sub_title: "Dr Louise Edensor SFHEA",
              icon: "",
            },
            {
              slug: "fees_total",
              title: "FEES",
              sub_title: "AED 59,947 PER YEAR",
              icon: "",
            },
          ],
        },
      },
      {
        slug: "mdx_coursebox",
        data: {
          scrollID: null,
          title: null,
          main_title: null,
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          tab: [
            {
              tab_item: {
                title: "DURATION",
                icon: "",
                content: "SEPTEMBER",
              },
              tab_result: {
                video: {
                  url: "",
                  poster: "",
                  iframe: false,
                },
                title: "WHY CHOOSE MDX DUBAI?",
                content: "",
              },
            },
            {
              tab_item: {
                title: "DURATION",
                icon: "",
                content: "3 YEARS",
              },
              tab_result: "",
            },
            {
              tab_item: {
                title: "ATTENDANCE",
                icon: "",
                content: "FULL TIME",
              },
              tab_result: "",
            },
            {
              tab_item: {
                title: "COURSE LEADER",
                icon: "",
                content: "DR PALLAVI KISHORE FCCA UAECA SFHEA",
              },
              tab_result: "",
            },
            {
              tab_item: {
                title: "FEES",
                icon: "",
                content: "AED 59,947 PER YEAR",
              },
              tab_result: "",
            },
          ],
        },
      },
      {
        slug: "mdx_accreditation",
        data: {
          scrollID: null,
          title: null,
          main_title: null,
          content:
            "<p>All students who complete our BA (Honours) Accounting and Finance degree can apply to any of the accountancy bodies for exemptions. A graduate can then sit more professional exams and work towards becoming a chartered accountant. Starting in a traineeship position, there are various career pathways to choose from including: audit, taxation, budget analysis, financial accounting and management accounting.</p>",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          cards: [
            {
              img: "",
              title: "THE ASSOCIATION OF CHARTERED CERTIFIED ACCOUNTANTS (ACCA)",
              content:
                "<p>The ACCA is the fastest growing, most supportive gateway to your career in accountancy, finance, business and management. The ACCA Qualification will arm you with the skills and experience to build a successful career anywhere in the world. With their strong presence in 181 countries around the world, your skills will be in demand internationally.</p>",
              link: {
                url: "#",
                text: "Read More",
              },
            },
            {
              img: "",
              title: "THE INSTITUTE OF CHARTERED ACCOUNTANTS IN ENGLAND AND WALES (ICAEW)",
              content:
                "<p>The ICAEW is a world leading professional membership organisation that promotes, develops and supports over 142,000 chartered accountants worldwide. They provide qualifications and professional development, share knowledge, insight and technical expertise, and protect the quality and integrity of the accountancy and finance profession.</p>",
              link: {
                url: "#",
                text: "Read More",
              },
            },
            {
              img: "",
              title: "THE CHARTERED INSTITUTE OF MANAGEMENT ACCOUNTANTS (CIMA)",
              content:
                "<p>The CIMA is a globally recognised professional qualification in accounting, business and finance. Students are eligible for exemptions from CIMA meaning you have will have completed part of your professional qualification as part of your degree.</p>",
              link: {
                url: "#",
                text: "Read More",
              },
            },
            {
              img: "",
              title: "CFA INSTITUTE",
              content:
                "<p>The BA (Honours) Accounting and Finance is affiliated by the CFA Institute, an industry organisation for Chartered Financial Analysts that offers educational resources and advocates for transparent, ethical and accountable investment for the benefit of society.</p>",
              link: {
                url: "#",
                text: "Read More",
              },
            },
            {
              img: "",
              title: "LOREM IPSUM",
              content:
                "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>",
              link: {
                url: "#",
                text: "Read More",
              },
            },
          ],
        },
      },
      {
        slug: "mdx_benefits",
        data: {
          scrollID: null,
          title: null,
          main_title: null,
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          cards: [
            {
              count: "01",
              content: "Gain maximum exemptions from ACCA, CIMA and ICAEW",
            },
            {
              count: "02",
              content: "The programme is affiliated with the CFA Institute",
            },
            {
              count: "03",
              content:
                "Regular opportunities to interact with finance professionals in discourse sessions and guest lectures",
            },
            {
              count: "04",
              content:
                "Information session and interaction with accounting and finance professional bodies on",
            },
            {
              count: "05",
              content:
                "Opportunity to gain professional certifications in industry computer software to enhance",
            },
            {
              count: "06",
              content: "Opportunity to start ACCA while studying the undergraduate programme",
            },
            {
              count: "07",
              content: "ACCA Accelerate scheme offers further reduction in exam fees",
            },
            {
              count: "08",
              content:
                "Become CIMA Student member as an undergraduate student, included in your tuition fees",
            },
            {
              count: "09",
              content: "Participate in exclusive career days for Accounting and Finance students",
            },
          ],
        },
      },
      {
        slug: "mdx_programme_module",
        data: {
          scrollID: null,
          title: null,
          main_title: null,
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },

          featured_img: {
            url: "",
            alt: "",
          },
          tab: [
            {
              title: "Year 1",
              accordion: true,
              content: [
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
              ],
            },
            {
              title: "Year 2",
              accordion: true,
              content: [
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
              ],
            },
            {
              title: "Year 3",
              accordion: true,
              content: [
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
                {
                  acc_title: "",
                  acc_content: "",
                },
              ],
            },
          ],
          note: {
            title: "Please Note:",
            content:
              "<p>Both core and optional modules are constantly updated and reviewed. A module may change or may not be offered a particular academic year, for reasons such as too few students choose that particular module or the module requires academic review. Middlesex University Dubai reserves the right to vary or withdraw any course or module at any time.</p>",
          },
        },
      },
      {
        slug: "mdx_programme_content",
        data: {
          scrollID: null,
          title: "WHAT YOU WILL STUDY ON YOUR BA HONOURS ACCOUNTING & FINANCE PROGRAMME",
          main_title: "PROGRAMME CONTENT",
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },

          tab: [
            {
              title: "The Pivotal Role of Accounting in Organisational Success",
              accordion: false,
              content:
                "<p>Our three-year degree covers the key areas of Financial Accounting, Management Accounting, Finance, Taxation and Business Law. You will also choose from an extensive range of modules that explore the broader business environment and gain an understanding of the pivotal role of accounting to the success of organisations across the globe.</p><p>You will develop a set of transferable skills to support you on your career journey, such as advanced analytical thinking and problem solving. You will learn how to work effectively in teams as both a leader and collaborator and become a confident communicator both written and verbally, ensuring you can communicate effectively in a business environment.</p>",
            },
            {
              title: "Gain a solid grounding in Accounting & Finance",
              accordion: false,
              content: "",
            },
            {
              title: "Advance your skills and knowledge",
              accordion: false,
              content: "",
            },
          ],
        },
      },
      {
        slug: "mdx_course_overview",
        data: {
          scrollID: null,
          title: "",
          main_title: "COURSE OVERVIE",
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          cards: [
            {
              title: "INTAKE",
              content: "SEPTEMBER",
            },
            {
              title: "DURATION",
              content: "3 YEARS",
            },
            {
              title: "ATTENDANCE",
              content: "FULL TIME",
            },
            {
              title: "COURSE LEADER",
              content: "DR PALLAVI KISHORE FCCA UAECA SFHEA",
            },
            {
              title: "TOTAL FEES",
              content: "AED 179,841 (3 YEARS) AED 59,947 PER YEAR",
            },
          ],
        },
      },
      {
        slug: "mdx_requirement",
        data: {
          scrollID: null,
          title: "",
          main_title: "ENTRY REQUIREMENTS",
          content: "",
          background_color: null,
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          tab: [
            {
              title: "Indian Secondary School Certificates / CBSE",
              content:
                "<h2>Indian Secondary School Certificates / CBSE</h2><p>Direct entry into year 1 of our Undergraduate Degree Programmes can be accessed through many curriculums, the most common of which are below. However entry requirements may vary by programme and various other factors, so if your curriculum is not mentioned below please submit your application and a member of our admissions department will connect with you to discuss further.</p>",
            },
            {
              title: "",
              content: "",
            },
            {
              title: "",
              content: "",
            },
            {
              title: "",
              content: "",
            },
            {
              title: "",
              content: "",
            },
            {
              title: "",
              content: "",
            },
            {
              title: "",
              content: "",
            },
          ],
        },
      },
      {
        slug: "rich_text_widget",
      },
      {
        slug: "mdx_industry_exp ",
        data: {
          scrollID: null,
          title: "",
          main_title: "WORLD-CLASS FACULTY WITH A WEALTH OF  INDUSTRY EXPERIENCE",
          content:
            "<p>Classes are held at Dubai Knowledge Park campus Monday to Friday, between 8:30am and 5:30pm. No classes are scheduled on Fridays between 12.00pm and 2.00pm. Occasional sessions may be scheduled over weekends or holiday periods, and you can expect plenty of notice for these. Attending scheduled weekly classes is an important requirement for completion of the programme.</p><p>Students will be involved in a range of learning, teaching, and assessment approaches. Such approaches aim to put students at the centre of their own learning so that they are engaged and involved in all aspects. The programme requires active involvement and collaboration with fellow students, including working and learning as part of small groups. Learning activities may occur both within and outside the classroom.</p><p>Students will be supported by technology, and faculty will use existing and emerging tech to engage with students. The programme may be facilitated using a variety of online tools (My Learning on UniHub, podcasts, wikis, etc.). By engaging with e-learning, students will be developing additional skills highly valued by employers. These include working flexibly, communication, understanding of IT, and team working.</p>",
          background_color: null,
          background_image: "",
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
        },
      },
      {
        slug: "mdx_careerhub",
        data: {
          scrollID: null,
          title: "",
          main_title: "WHERE YOUR UK DEGREE WILL TAKE YOUR CAREER.",
          content:
            "<p>An Accounting and Finance degree opens the doors to a range of careers, many with excellent progression and competitive salaries. You can also pursue a career as a professional accountant following accreditation. Middlesex Accounting and Finance graduates progress into careers with a wide range of prestigious organisations in the following roles: Trainee Accountant, Accounts Assistant, Audit Trainee, Financial Risk Analyst, Finance Assistant and Credit Controller. Previous graduates have progressed into careers with a wide range of prestigious organisations including:</p> <ul><li>Deloitte</li><li>EY</li><li>KPMG</li><li>PwC</li><li>Grant Thornton</li><li>Middlesex University Dubai</li><li>Al Futtaim Logistics</li><li>Aurifer</li><li>VFS</li><li>Sephora</li><li>Swarovski</li><li>Emirates NBD</li></ul><p>You can also go on to further study on courses such as our MSc Investment Management and MSc Banking and Finance.</p>",
          background_color: null,
          background_image: "",
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
        },
      },
      {
        slug: "mdx_faculties",
        data: {
          scrollID: null,
          title: "BA HONOURS ACCOUNTING AND FINANCE ",
          main_title: "FACULTY",
          content: "",
          background_color: null,
          background_image: "",
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          cards: [
            {
              image: {
                url: "",
                alt: "",
              },
              title: "DR PALLAVI KISHORE SFHEA FCCA UAECA",
              designation:
                "Head of Accounting and Finance, Campus Programme Coordinator - Undergraduate and Postgraduate Accounting and Finance, Senior Lecturer",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              designation: "",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              designation: "",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              designation: "",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              designation: "",
              link: "",
            },
          ],
        },
      },
      {
        slug: "mdx_contact_section",
        data: {
          scrollID: "CONTACT US",
          backgound_img: "/uploads/course_map_bg_min_8cb2121ca8.png",
          title: "",
          form: {
            title: "DON’T HESITATE TO CONTACT US",
            url: "",
          },
          address: {
            title: "OUR ADDRESS",
            content:
              "<p>Middlesex University Dubai, Dubai Knowledge Park - Blocks 15, 16 &amp; 17, P.O. Box 500697, Dubai, United Arab Emirates</p>",
          },
          contact: {
            title: "Our contact",
            phone: ["+971 (0)4 3678100"],
            email: ["info@mdx.ac.ae", "admissions@mdx.ac.ae"],
          },
          connect: {
            title: "FOLLOW US",
            social_media: [
              {
                name: "twitter",
                link: "https://twitter.com/MiddlesexDubai",
                image: "",
              },
              {
                name: "facebook",
                link: "https://www.facebook.com/MiddlesexDubai",
                image: "",
              },
              {
                name: "instagram",
                link: "https://www.instagram.com/middlesexdubai/",
                image: "",
              },
              {
                name: "linkedin",
                link: "https://www.linkedin.com/school/middlesexdubai/",
                image: "",
              },
              {
                name: " snapchat",
                link: "https://www.mdx.ac.ae/images/default-source/Social-media/snapcode-mdx.png",
                image: "",
              },
            ],
          },
          location: {
            title: "FIND US ON GOOGLE MAP",
            iframe: "",
          },
        },
      },
      {
        slug: "mdx_faculties",
        data: {
          scrollID: null,
          title: "",
          main_title: "RELATED COURSES",
          content: "",
          background_color: null,
          background_image: "",
          text_color: null,
          container: false,
          no_gutter: true,
          no_spacing: {
            all: false,
            top: false,
            bottom: false,
            left: false,
            right: false,
            x: false,
          },
          cards: [
            {
              image: {
                url: "",
                alt: "",
              },
              title: "BSC HONOURS BUSINESS ACCOUNTING",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              link: "",
            },
            {
              image: {
                url: "",
                alt: "",
              },
              title: "",
              link: "",
            },
          ],
        },
      },
    ],
  },
};

// export const data = {
//   data: {
//     header_script: null,
//     custom_css: null,
//     no_follow: false,
//     no_index: false,
//     cta_enabled: false,
//     enable_header: true,
//     enable_footer: true,
//     widgets: [
//       /* {
//         slug: "inner_banner",
//         backend_component_id: "generic-components.inne-banner",
//         data: {
//           sub_title: "1st Asia-Middle East-Africa",
//           center_align: true,
//           course_page: false,
//           contact_form: false,
//           hide_secroll_down: true,
//           title: "Conference on Academic and Research Integrity ACARI 2023",
//           img: "/uploads/buildings_1839726_1920_45c8ace8a7.jpg",
//           form_id: null,
//           form_type: null,
//           mobile_banner_img: "",
//           title_container: true,
//           spacing: {
//             xl: true,
//           },
//           no_spacing: {
//             bottom: true,
//           },
//           course_icon_strip: "",
//         },
//       }, */
//       {
//         slug: "Slim_banner",
//         backend_component_id: "generic-components.slim-banner",
//         data: {
//           title: "",
//           main_title: "The Centre of Continuous Learning and Outreach",
//           img: "/uploads/Job%20Applied%20Cover%20Letter/114d201f9ead41dc3aa9985214c08cff7b5e616c_mdx_dubai_banner.jpg?updated_at=2022-11-30T07:31:42.862Z",
//           media_type: "image",
//         },
//       },
//       {
//         backend_component_id: "generic-components.sidebar-layout",
//         slug: "sidebar_layout",
//         sidebar_links: [
//           "About",
//           "Divisions",
//           "Our Partners",
//           "Upcoming Events",
//           "Meet the team",
//         ],
//         children: [
//           {
//             slug: "AboutIntroWidget",
//             data: {
//               scrollID: "About",
//               title: "About",
//               form: {
//                 id: 8,
//                 title: "CONTACT US",
//                 type: "hbspot_form",
//                 link: "form_link",
//                 active_status: true,
//               },
//               content:
//                 '<p><span lang="EN-US" dir="ltr">Asia – Middle East – Africa (AMEA) as a region is an emerging market for global, world-class international education and research. Hosted by Middlesex University Dubai, UAE, colleagues from Centre for Academic Integrity at Canakkale Onsekiz Mart University, Türkiye University of Wollongong in Dubai, UAE, Lahore LEADS University, Pakistan and King Fahd Medical City, Saudi Arabia are organising the first regional, collaborative conference on academic and research integrity for the region – ACARI 2023.&nbsp;</span></p><p><span lang="EN-US" dir="ltr">With invited colleagues from Chitkara University, India, Kuwait University, Kuwait, Bangamata Sheikh Fojilatunnesa Mujib Science &amp; Technology University, Bangladesh, and University of Calgary in Qatar, ACARI 2023 aims to bring together leaders, educators, practitioners, and researchers from the AMEA region and beyond to discuss, create and promote the culture of integrity across educational campuses in their countries.&nbsp;</span></p><p><span lang="EN-US" dir="ltr">The conference will feature oral and poster presentations, keynotes from renowned practitioners and scholars, panel sessions, workshops and student competitions.&nbsp;</span></p><p><span lang="EN-US" dir="ltr">Academicians, practitioners, and research scholars wishing to present at the conference are invited to submit a 500-750-word abstract of continuous text describing their current work for consideration by the programme committee.</span></p>',
//             },
//           },
//           {
//             slug: "card_stack",
//             data: {
//               scrollID: "Divisions",
//               card_type: "image_box_content_card",
//               theme: "dark",
//               title: "Divisions",
//               columns: {
//                 id: 36,
//                 lg: 3,
//                 md: 2,
//                 xl: 4,
//               },
//               container: true,
//               // no_spacing: {
//               //   top: true,
//               // },
//               cards: [
//                 {
//                   static: true,
//                   title: "University Experience Programme",
//                   description:
//                     "Are you or your child aged 14-21 years old? Are you curious about life in Dubai? Do you want to practice your English language skills in a location with a difference?",
//                   img: "https://api.mdx.ac.ae/uploads/about_1c376dade2.jpg",
//                   link: "/mdx-experience",
//                 },
//                 {
//                   static: true,
//                   title:
//                     "MDX Professional <small class='d-block mt-2'> Short Courses, Professional Certifications etc.</small>",
//                   description:
//                     "Make an immediate impact and reignite learning and career development. Enrol in one of our short programmes and find the best solution to continued professional development for yourself and your team. You will be provided with the skillset to achieve and deliver results.",
//                   img: "https://api.mdx.ac.ae/uploads/mdx_professional_390a362435.jpeg?updated_at=2023-01-19T10:45:50.165Z",
//                   link: "/mdx-professional",
//                 },
//                 {
//                   static: true,
//                   title: "MDX Teaching and Learning Space",
//                   description:
//                     "Middlesex University Dubai is the largest and leading UK University in Dubai, located in the heart of the Dubai in Knowledge Park across 3 buildings. Learning spaces have evolved over the years, from traditional lecture style classrooms to technology-enhanced work stations that promote collaborative teaching and learning.",
//                   img: "https://api.mdx.ac.ae/uploads/mdx_teaching_7f248d5962.jpeg?updated_at=2023-01-19T10:45:50.955Z",
//                   link: "/mdx-collaborative-teaching-and-learning-experience",
//                 },
//                 {
//                   static: true,
//                   title: "MDX Pre-University Workshops ",
//                   description:
//                     "The Pre-University Workshop Series is an immersive and dynamic series of workshops that is available for driven and innovative students preparing for their future at university and want to get ahead of the game, whilst at the same time, familiarising yourself with Dubai and what life has to offer, making friends early, getting to know the campus and faculty ahead of September.",
//                   img: "https://api.mdx.ac.ae/uploads/mdx_pre_university_bd1d123ad6.png?updated_at=2023-01-19T10:45:51.896Z",
//                   link: "/mdx-pre-university-workshops",
//                 },
//                 {
//                   static: true,
//                   title: "MDX English Testing and Pre-Sessional",
//                   description:
//                     "Middlesex University Dubai promotes English language learning and support to make the transition to university a simple and seamless process.",
//                   img: "https://api.mdx.ac.ae/uploads/pre_university_workshops_ee280e372e.jpeg?updated_at=2023-01-19T10:45:50.895Z",
//                   link: "/english-language",
//                 },
//                 {
//                   static: true,
//                   title: "Academic Study Tour",
//                   description:
//                     "Education is one of the most important investments in life, especially when you get to experience studying in a different country at the same time. Academic study tours can play a major part in enhancing our current university experience or assist in making the right choice of what to study and where.",
//                   img: "https://api.mdx.ac.ae/uploads/institute_of_sustainable_63ca53a546.jpeg?updated_at=2023-01-19T10:45:49.124Z",
//                   link: "/academic-study-tours-in-dubai",
//                 },
//               ],
//             },
//           },
//           {
//             slug: "logo_slider_widget",

//             data: {
//               scrollID: "Our Partners",
//               title: "Our Partners",
//               main_title: "Global Partners",
//               description: null,
//               logo: [
//                 {
//                   img: "https://api.mdx.ac.ae/uploads/logo_slide_01_1615d7b068.png?updated_at=2023-01-19T10:42:57.527Z",
//                   width: 500,
//                   height: 180,
//                 },
//                 {
//                   img: "https://api.mdx.ac.ae/uploads/logo_slide_03_67dae280ee.png?updated_at=2023-01-19T10:42:57.545Z",
//                   width: 500,
//                   height: 180,
//                 },
//                 {
//                   img: "https://api.mdx.ac.ae/uploads/logo_slide_02_30945c3d17.png?updated_at=2023-01-19T10:42:57.551Z",
//                   width: 500,
//                   height: 180,
//                 },
//                 {
//                   img: "https://api.mdx.ac.ae/uploads/logo_slide_04_b7da222fac.png?updated_at=2023-01-19T10:42:57.559Z",
//                   width: 500,
//                   height: 180,
//                 },
//                 {
//                   img: "https://api.mdx.ac.ae/uploads/logo_slide_05_423b5a352b.png?updated_at=2023-01-19T10:42:57.580Z",
//                   width: 500,
//                   height: 180,
//                 },
//               ],
//             },
//           },
//           {
//             slug: "UpcomingEventWidget",
//             data: {
//               scrollID: "Upcoming Events",
//               title: "Upcoming Events",
//               content: ``,
//               image: "",
//               title: "What’s On",
//               events: {
//                 db_data: "related_events",
//               },
//               event_title: "Upcoming events",
//               join_event_title: "Join an event",
//               related_events: [
//                 {
//                   id: 360,
//                   title: "Middlesex University Dubai visits Trichi",
//                   slug: "21-jan-mdx-visits-trichi",
//                   code: "",
//                   start_date: "2023-01-21",
//                   end_date: "2023-01-21",
//                   utc_time: "2023-01-21T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "21-jan-mdx-visits-trichi",
//                 },
//                 {
//                   id: 361,
//                   title: "Middlesex University Dubai visits Coimbatore",
//                   slug: "23-jan-mdx-visits-coimbatore",
//                   code: "",
//                   start_date: "2023-01-23",
//                   end_date: "2023-01-23",
//                   utc_time: "2023-01-23T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "23-jan-mdx-visits-coimbatore",
//                 },
//                 {
//                   id: 392,
//                   title: "Meet MDX Dubai at Gaudeamus Prague 2023",
//                   slug: "events-meet-mdx-dubai-at-gaudeamus-prague",
//                   code: "",
//                   start_date: "2023-01-24",
//                   end_date: "2023-01-26",
//                   utc_time: "2023-01-24T07:00:00.000Z",
//                   start_time: "12:30:00",
//                   full_time_string: "07:00 am GST",
//                   end_time: "15:00:00",
//                   event_cat_id: 1,
//                   description:
//                     "<p>Meet our Admissions Counsellor Egi Shalzi in Prague on Jan 24 - 26, from 8am-4pm (CET) to find out about our UK programmes that you can study in the amazing city of Dubai! You can learn about:&nbsp;</p><ul><li>Which of our 70+ UK programmes might be right for your ambitions and interests</li><li>Our scholarships and grants for students from Europe</li><li>Extracurricular opportunities open to you as part our unrivalled student experience</li><li>The careers and employability support available that will help you launch your global career</li><li>Simple, quick visa process</li><li>How to submit your application</li></ul>",
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "events/meet-mdx-dubai-at-gaudeamus-prague",
//                 },
//                 {
//                   id: 362,
//                   title: "Middlesex University Dubai visits Kochi",
//                   slug: "25-jan-mdx-visits-kochi",
//                   code: "",
//                   start_date: "2023-01-25",
//                   end_date: "2023-01-26",
//                   utc_time: "2023-01-25T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "25-jan-mdx-visits-kochi",
//                 },
//                 {
//                   id: 389,
//                   title: "Employability Bootcamp – In-person Series",
//                   slug: "ces-employability-bootcamp-in-person-series",
//                   code: "",
//                   start_date: "2023-01-25",
//                   end_date: "2023-01-25",
//                   utc_time: "2023-01-25T06:45:00.000Z",
//                   start_time: "12:15:00",
//                   full_time_string: "06:45 am GST",
//                   end_time: "11:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-GB" dir="ltr"><strong>Date:&nbsp;Wednesday, 25 January 2023</strong></span></p><p><span lang="EN-US" dir="ltr"><strong>Time:&nbsp; 10:45 AM – 15:00 PM</strong></span></p><p><span lang="EN-GB" dir="ltr">Bookmark your calendars and check this site after 16th January 2023 for details of the Agenda and how you can get involved.</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "ces/employability-bootcamp-in-person-series",
//                 },
//                 {
//                   id: 363,
//                   title: "Middlesex University Dubai visits Kochi",
//                   slug: "26-jan-mdx-visits-kochi",
//                   code: "",
//                   start_date: "2023-01-26",
//                   end_date: "2023-01-26",
//                   utc_time: "2023-01-26T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "26-jan-mdx-visits-kochi",
//                 },
//                 {
//                   id: 346,
//                   title:
//                     "B!G THINK - UG Business School Industry Analysis Poster Competition",
//                   slug: "event-bigthink",
//                   code: "",
//                   start_date: "2023-02-01",
//                   end_date: "2023-02-02",
//                   utc_time: "2023-02-01T07:00:00.000Z",
//                   start_time: "12:30:00",
//                   full_time_string: "07:00 am GST",
//                   end_time: "11:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p>Students in the IFP and Undergraduate Business Programmes are invited to enter the MDX UG Business School’s Industry Analysis Poster Competition!&nbsp;</p><p>The competition is based on the assessment of a company’s Macro environment (linked with your Term 1 assessments). The competition will showcase your analytical skills, and posters will be displayed in the university for judging to take place, and the opportunity to win exciting prizes!</p><p><strong>Team registration deadline:</strong> 20th January 2023</p><p><strong>Final poster submission deadline:</strong> 26th January 2023</p><p><strong>Showcase and Winner Announcements:</strong>&nbsp;</p><p>IFP and 1st Year: Feb 1st 2023, 11am onwards</p><p>2nd Year and 3rd Year: Feb 2nd 2023, 11am onwards</p><p>Open area between Blocks 15, 16 &amp; 17, Knowledge Park</p><p>&nbsp;</p><p><strong>To register please follow the relevant directions below:&nbsp;</strong></p><p><a href="https://www.mdx.ac.ae/IFPbigthink2022"><strong>International Foundation Programme Students&nbsp;</strong></a></p><p><a href="https://www.mdx.ac.ae/y1bigthink2022"><strong>Year 1 Students</strong></a><strong>&nbsp;</strong></p><p><a href="https://www.mdx.ac.ae/y2bigthink2022"><strong>Year 2 Students</strong></a></p><p><a href="https://www.mdx.ac.ae/y3bigthink2022"><strong>Year 3 Students</strong></a></p><p>&nbsp;</p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "event/bigthink",
//                 },
//                 {
//                   id: 375,
//                   title: "Middlesex University Dubai visits Karachi",
//                   slug: "4-feb-mdx-visits-karachi",
//                   code: "",
//                   start_date: "2023-02-04",
//                   end_date: "2023-02-04",
//                   utc_time: "2023-02-04T06:00:00.000Z",
//                   start_time: "11:30:00",
//                   full_time_string: "06:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the Dawn Education Expo</span><br><br><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "4-feb-mdx-visits-karachi",
//                 },
//                 {
//                   id: 391,
//                   title: "Middlesex University Dubai visits Karachi",
//                   slug: "5-feb-mdx-visits-karachi",
//                   code: "",
//                   start_date: "2023-02-05",
//                   end_date: "2023-02-04",
//                   utc_time: "2023-02-05T06:00:00.000Z",
//                   start_time: "11:30:00",
//                   full_time_string: "06:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the Dawn Education Expo</span><br><br><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "5-feb-mdx-visits-karachi",
//                 },
//                 {
//                   id: 364,
//                   title: "Middlesex University Dubai visits Bahrain",
//                   slug: "9-feb-mdx-visits-bahrain",
//                   code: "",
//                   start_date: "2023-02-09",
//                   end_date: "2023-02-09",
//                   utc_time: "2023-02-09T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p><p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the JnS Exhibition</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "9-feb-mdx-visits-bahrain",
//                 },
//                 {
//                   id: 365,
//                   title: "Middlesex University Dubai visits Qatar",
//                   slug: "10-feb-mdx-visits-qatar",
//                   code: "",
//                   start_date: "2023-02-10",
//                   end_date: "2023-02-10",
//                   utc_time: "2023-02-10T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p><p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the JnS Exhibition</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "10-feb-mdx-visits-qatar",
//                 },
//                 {
//                   id: 366,
//                   title: "Middlesex University Dubai visits Kuwait",
//                   slug: "11-feb-mdx-visits-kuwait",
//                   code: "",
//                   start_date: "2023-02-11",
//                   end_date: "2023-02-12",
//                   utc_time: "2023-02-11T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p><p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the JnS Exhibition</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "11-feb-mdx-visits-kuwait",
//                 },
//                 {
//                   id: 367,
//                   title: "Middlesex University Dubai visits Kuwait",
//                   slug: "12-feb-mdx-visits-kuwait",
//                   code: "",
//                   start_date: "2023-02-11",
//                   end_date: "2023-02-11",
//                   utc_time: "2023-02-11T20:00:00.000Z",
//                   start_time: "01:30:00",
//                   full_time_string: "08:00 pm GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p><p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Meet us at the JnS Exhibition</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "12-feb-mdx-visits-kuwait",
//                 },
//                 {
//                   id: 379,
//                   title: "Middlesex University Dubai visits Cote D’Ivoire",
//                   slug: "13-feb-mdx-visits-cote-d-ivoire",
//                   code: "",
//                   start_date: "2023-02-13",
//                   end_date: "2023-02-15",
//                   utc_time: "2023-02-13T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us in Abidjan</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "13-feb-mdx-visits-cote-d-ivoire",
//                 },
//                 {
//                   id: 380,
//                   title: "Middlesex University Dubai visits Cote D’Ivoire",
//                   slug: "14-feb-mdx-visits-cote-d-ivoire",
//                   code: "",
//                   start_date: "2023-02-14",
//                   end_date: "2023-02-15",
//                   utc_time: "2023-02-14T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us in Abidjan</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "14-feb-mdx-visits-cote-d-ivoire",
//                 },
//                 {
//                   id: 381,
//                   title: "Middlesex University Dubai visits Cote D’Ivoire",
//                   slug: "15-feb-mdx-visits-cote-d-ivoire",
//                   code: "",
//                   start_date: "2023-02-15",
//                   end_date: "2023-02-15",
//                   utc_time: "2023-02-15T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us in Abidjan</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "15-feb-mdx-visits-cote-d-ivoire",
//                 },
//                 {
//                   id: 390,
//                   title: "Career Fairs 2023",
//                   slug: "ces-career-fairs-2023",
//                   code: "",
//                   start_date: "2023-02-15",
//                   end_date: "2023-02-16",
//                   utc_time: "2023-02-15T06:45:00.000Z",
//                   start_time: "12:15:00",
//                   full_time_string: "06:45 am GST",
//                   end_time: "11:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-GB" dir="ltr">The </span><a href="https://www.mdx.ac.ae/ces"><span lang="EN-GB" dir="ltr">Careers and Employability Services</span></a><span lang="EN-GB" dir="ltr"> Department at Middlesex University Dubai announces that the Career Fairs 2023 will be held on the <strong>15th and 16th of February, 2023</strong>. If you are a student or a recent alumni, you can sign-up to attend starting 01 February 2023.&nbsp;</span></p><p><span lang="EN-GB" dir="ltr"><strong>About Career Fairs 2023</strong></span></p><p><span lang="EN-GB" dir="ltr">This event will host over 100 companies in a 2-day format, ranging from start-ups and SMEs to MNCs such as Emirates Airlines, the Chalhoub Group, Grohe, and Apparel Group. The Career Fairs aim to connect our students and recent graduates with leading employers across a range of industries and create a collaborative advantage that will allow employers to benefit from the skills and expertise of our students and graduates.&nbsp;</span></p><p><span lang="EN-GB" dir="ltr">Middlesex University Dubai has a proven track record of successful career events. The most recent event </span><a href="https://www.mdx.ac.ae/news/looking-back-on-gradstock-employability-festival-2022"><span lang="EN-GB" dir="ltr">Gradstock Career Festival 2022</span></a><span lang="EN-GB" dir="ltr">, held in October 2022, was a resounding success and had over 45 companies engaging with 500+ students. Last year\'s Career Days garnered the participation of over 130 organisations and 700 students and graduates. These Fairs include a mix of sessions dedicated to resume writing, personal branding, public speaking, networking opportunities, and alumni panel discussions, all of which have been highly beneficial to our students and contributed to their employability.</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "ces/career-fairs-2023",
//                 },
//                 {
//                   id: 382,
//                   title: "Middlesex University Dubai visits Cote D’Ivoire",
//                   slug: "16-feb-mdx-visits-cote-d-ivoire",
//                   code: "",
//                   start_date: "2023-02-16",
//                   end_date: "2023-02-15",
//                   utc_time: "2023-02-16T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us in Abidjan</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "16-feb-mdx-visits-cote-d-ivoire",
//                 },
//                 {
//                   id: 383,
//                   title: "Middlesex University Dubai visits Senegal",
//                   slug: "17-feb-mdx-visits-senegal",
//                   code: "",
//                   start_date: "2023-02-17",
//                   end_date: "2023-02-18",
//                   utc_time: "2023-02-17T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-US" dir="ltr">Meet us in Dakar</span></p><p><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "17-feb-mdx-visits-senegal",
//                 },
//                 {
//                   id: 384,
//                   title: "Middlesex University Dubai visits Senegal",
//                   slug: "18-feb-mdx-visits-senegal",
//                   code: "",
//                   start_date: "2023-02-18",
//                   end_date: "2023-02-18",
//                   utc_time: "2023-02-18T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-US" dir="ltr">Meet us in Dakar</span></p><p><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "18-feb-mdx-visits-senegal",
//                 },
//                 {
//                   id: 385,
//                   title: "Middlesex University Dubai visits Senegal",
//                   slug: "19-feb-mdx-visits-senegal",
//                   code: "",
//                   start_date: "2023-02-18",
//                   end_date: "2023-02-18",
//                   utc_time: "2023-02-18T20:00:00.000Z",
//                   start_time: "01:30:00",
//                   full_time_string: "08:00 pm GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-US" dir="ltr">Meet us in Dakar</span></p><p><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "19-feb-mdx-visits-senegal",
//                 },
//                 {
//                   id: 356,
//                   title: "Middlesex University Dubai visits Qatar",
//                   slug: "21-feb-mdx-visits-qatar",
//                   code: "",
//                   start_date: "2023-02-21",
//                   end_date: "2023-02-23",
//                   utc_time: "2023-02-21T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "21-feb-mdx-visits-qatar",
//                 },
//                 {
//                   id: 357,
//                   title: "Middlesex University Dubai visits Qatar",
//                   slug: "22-feb-mdx-visits-qatar",
//                   code: "",
//                   start_date: "2023-02-22",
//                   end_date: "2023-02-23",
//                   utc_time: "2023-02-22T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "22-feb-mdx-visits-qatar",
//                 },
//                 {
//                   id: 358,
//                   title: "Middlesex University Dubai visits Qatar",
//                   slug: "23-feb-mdx-visits-qatar",
//                   code: "",
//                   start_date: "2023-02-23",
//                   end_date: "2023-02-23",
//                   utc_time: "2023-02-23T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "23-feb-mdx-visits-qatar",
//                 },
//                 {
//                   id: 376,
//                   title: "Middlesex University Dubai visits Prague",
//                   slug: "24-feb-mdx-visits-prague",
//                   code: "",
//                   start_date: "2023-02-24",
//                   end_date: "2023-02-25",
//                   utc_time: "2023-02-24T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us at Gaudeamus PRAHA 2023</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "24-feb-mdx-visits-prague",
//                 },
//                 {
//                   id: 377,
//                   title: "Middlesex University Dubai visits Prague",
//                   slug: "25-feb-mdx-visits-prague",
//                   code: "",
//                   start_date: "2023-02-25",
//                   end_date: "2023-02-25",
//                   utc_time: "2023-02-25T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us at Gaudeamus PRAHA 2023</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "25-feb-mdx-visits-prague",
//                 },
//                 {
//                   id: 351,
//                   title: "Middlesex University Dubai visits Saudi",
//                   slug: "26-feb-mdx-visits-saudi",
//                   code: "",
//                   start_date: "2023-02-26",
//                   end_date: "2023-02-28",
//                   utc_time: "2023-02-26T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "26-feb-mdx-visits-saudi",
//                 },
//                 {
//                   id: 378,
//                   title: "Middlesex University Dubai visits Prague",
//                   slug: "26-feb-mdx-visits-prague",
//                   code: "",
//                   start_date: "2023-02-26",
//                   end_date: "2023-02-25",
//                   utc_time: "2023-02-26T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Meet us at Gaudeamus PRAHA 2023</span></p><p style="margin-left:0cm;"><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "26-feb-mdx-visits-prague",
//                 },
//                 {
//                   id: 352,
//                   title: "Middlesex University Dubai visits Saudi",
//                   slug: "27-feb-mdx-visits-saudi",
//                   code: "",
//                   start_date: "2023-02-27",
//                   end_date: "2023-02-28",
//                   utc_time: "2023-02-27T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "27-feb-mdx-visits-saudi",
//                 },
//                 {
//                   id: 353,
//                   title: "Middlesex University Dubai visits Saudi",
//                   slug: "28-feb-mdx-visits-saudi",
//                   code: "",
//                   start_date: "2023-02-28",
//                   end_date: "2023-02-28",
//                   utc_time: "2023-02-28T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "28-feb-mdx-visits-saudi",
//                 },
//                 {
//                   id: 354,
//                   title: "Middlesex University Dubai visits Saudi",
//                   slug: "1-mar-mdx-visits-saudi",
//                   code: "",
//                   start_date: "2023-03-01",
//                   end_date: "2023-03-02",
//                   utc_time: "2023-03-01T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "13:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "1-mar-mdx-visits-saudi",
//                 },
//                 {
//                   id: 355,
//                   title: "Middlesex University Dubai visits Saudi",
//                   slug: "2-mar-mdx-visits-saudi",
//                   code: "",
//                   start_date: "2023-03-01",
//                   end_date: "2023-03-01",
//                   utc_time: "2023-03-01T20:00:00.000Z",
//                   start_time: "01:30:00",
//                   full_time_string: "08:00 pm GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span style="color:rgb(0,0,0);font-family:Calibri, sans-serif;">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "2-mar-mdx-visits-saudi",
//                 },
//                 {
//                   id: 386,
//                   title: "Middlesex University Dubai visits Bahrain",
//                   slug: "5-mar-mdx-visits-bahrain",
//                   code: "",
//                   start_date: "2023-03-05",
//                   end_date: "2023-03-05",
//                   utc_time: "2023-03-05T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "5-mar-mdx-visits-bahrain",
//                 },
//                 {
//                   id: 387,
//                   title: "Middlesex University Dubai visits Bahrain",
//                   slug: "6-mar-mdx-visits-bahrain",
//                   code: "",
//                   start_date: "2023-03-06",
//                   end_date: "2023-03-05",
//                   utc_time: "2023-03-06T04:00:00.000Z",
//                   start_time: "09:30:00",
//                   full_time_string: "04:00 am GST",
//                   end_time: "20:00:00",
//                   event_cat_id: 1,
//                   description:
//                     '<p><span lang="EN-US" dir="ltr">Confirm your place for September 2023</span></p>',
//                   is_active: 1,
//                   deleted_at: null,
//                   created_at: "2022-07-27T08:56:55.000000Z",
//                   updated_at: "2022-07-27T08:56:55.000000Z",
//                   created_by: 1,
//                   updated_by: null,
//                   links: "6-mar-mdx-visits-bahrain",
//                 },
//               ],
//             },
//           },
//           {
//             slug: "OurTeam",
//             backend_component_id: "generic-components.custom-staff-page",
//             data: {
//               scrollID: "Meet the team",
//               card_type: "faculty_card",
//               title: "Meet the team",
//               no_spacing: {
//                 top: true,
//               },
//               cards: [
//                 {
//                   name: "Stuart Kirkham",
//                   designation:
//                     "Head of Student Recruitment & Outreach <br/><a href='mailto:s.kirkham@mdx.ac.ae'>s.kirkham@mdx.ac.ae</a>",
//                   img: "https://api.mdx.ac.ae/uploads/Stuart_d93315f3bb.jpg",
//                   link: "",
//                 },
//                 {
//                   name: "Egi Shalzi",
//                   designation:
//                     "Student Recruitment Executive <br/><a href='tel:+971043658732'>+971 (0)4 365 8732</a><br/><a href='mailto:E.Shalzi@mdx.ac.ae'>E.Shalzi@mdx.ac.ae</a><br/><a href='tel:+971565008343'>+971 56 500 8343</a>",
//                   img: "https://api.mdx.ac.ae/uploads/egi_f296d8788f.jpg",
//                   link: "",
//                 },
//                 {
//                   name: "Luisa Ocampo",
//                   designation:
//                     "Business Development Coordinator <br/><a href='mailto:L.Ocampo@mdx.ac.ae'>L.Ocampo@mdx.ac.ae</a>",
//                   img: "https://api.mdx.ac.ae/uploads/louisa_b9e3af70f5.jpg",
//                   link: "",
//                 },
//               ],
//             },
//           },
//         ],
//       },
//     ],
//   },
// };
